server:
  port: 8081
elasticsearch:
  host: localhost
  port: 9200
spring:
  cloud:
    stream:
      kafka:
        binder:
          zkNodes: localhost:2181
          brokers: localhost:29092
      bindings:
        input:
          destination: delete-travel
index: "travel-*"

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
    health:
      elasticsearch:
        enabled: false
